### ISSUE TITLE
Problem in displaying status code

### ISSUE THREAD

**Issue by kavirajk** [rspivak/httpcode#9]
Problem in displaying status code while trying to list all the status code with 'less' command in Linux

Command used:
bash$: hc | less

output:
Status code ESC[1m100ESC[0m
Message: Continue
Code explanation: Request received, please continue

Status code ESC[1m101ESC[0m
Message: Switching Protocols
Code explanation: Switching to new protocol; obey Upgrade header

Status code ESC[1m200ESC[0m
Message: OK
Code explanation: Request fulfilled, document follows

Status code ESC[1m201ESC[0m
Message: Created
Code explanation: Document created, URL follows

Status code ESC[1m202ESC[0m
Message: Accepted
Code explanation: Request accepted, processing continues off-line

**Comment by manniche** [comment]
Which terminal are you using? If you use a VT-100 compatible terminal, you should check whether you have enabled support for formatting.

**Comment by kavirajk** [comment]
the changes are not merged into master branch??

**Comment by manniche** [comment]
I see them here: https://github.com/rspivak/httpcode/commit/b30a554ae922b59c5f0eb72179d7fba3c506fca5

**Comment by kavirajk** [comment]
Cool.. :)
